# Generated by Django 4.2.6 on 2023-12-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
